### ISSUE TITLE
Roadmap to release 1

### ISSUE THREAD

**Issue by indrora** [indrora/ponzu#5]
I figure now is as good a time as ever to outline the things that need to happen for release 1 of the spec, most of which are related to the reference archiver. 

non-archiver deficiencies:

- [ ] docs: need to finalize some wording
- [x] docs/theme: finish GOAT diagram work
- [ ] docs/theme: finish upstream pull request https://github.com/colinwilson/lotusdocs/pull/148
- [ ] format: SDDL strings??? (#4)

archiver deficiencies: 

- [x] #8
- [ ] #7
- [ ] parc/cmd/verify: cleaner implement

ponzu/lib deficiencies:

- [x] #6

**Comment by indrora** [comment]
Additional spots:

- [ ] Additional compressor options? I want to add S2 (used by MinIO) but there's only one reference compressor from @klauspost; I'm hesitant to add something that doesn't have a good description outside of a single reference implementation. 
- [ ] A "tape safe" version that indexes on 512byte blocks as an "extension"?
